### ISSUE TITLE
[Fight the systemic issue]

### ISSUE THREAD

**Issue by christopheml** [malk/please-review-me#1]
The "bad culture breeds bad software" idiom is a nice one to tackle, however I think this is a difficult workshop to do at a conference. You will need to start from a particular piece of software that's bad because of a bad culture, but how will you convey that culture to the participants ?

Even freshly recruited devs working on a legacy project have a sense of that corporate culture because they are quickly immersed in it. I may be hard to provide such immersion in a workshop.

**Comment by malk** [comment]
Thanks so much for the feedback:

This one Workshop I have already done some times already (last times at the Software Craftsmanship BoF at Devoxx) I have created an interactive kata using micro "sprints" to show people the effects

Up until no I do have very positive feedback, But I would love to doanother round with you and the other arolla folks and have some feedback :)
